name: Validate

on:
  push:
  pull_request:
    branches:
      - 2.x

env:
  SKIP_CI_SPECS: |
    components/fs/lustre-client/SPECS/lustre.spec

jobs:
  check_spec:
    env:
      JOB_SKIP_CI_SPECS: |
        components/admin/ohpc-filesystem/SPECS/ohpc-filesystem.spec

    runs-on: ubuntu-latest
    container:
      image: docker.io/library/rockylinux:8

    steps:
    - name: Setup
      run: |
        dnf install -y epel-release git python3
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Validate Changes
      run: |
        tests/ci/check_spec.py ${{ steps.files.outputs.added_modified }}

  lint:
    strategy:
      matrix:
        step: [codespell, flake8, shellcheck, whitespace]
    name: Run ${{ matrix.step }} linter
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:latest
    steps:
    - name: Setup
      run: dnf -y install codespell make python3-flake8 ShellCheck
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run ${{ matrix.step }}
      run: make -C tests/ci/ ${{ matrix.step }}-lint

  build_on_rhel:
    runs-on: ubuntu-latest
    name: Build on RHEL
    container:
      image: docker.io/library/rockylinux:8
    steps:
    - name: Install git
      run: dnf -y install git
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      run: tests/ci/prepare-ci-environment.sh
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Validate Build
      run: |
        . /etc/profile.d/lmod.sh
        tests/ci/run_build.py ohpc ${{ steps.files.outputs.added_modified }}
    - uses: actions/upload-artifact@v3
      with:
        name: rhel-rpms
        path: |
          /home/ohpc/rpmbuild/RPMS/noarch/*rpm
          /home/ohpc/rpmbuild/RPMS/x86_64/*rpm

  test_on_rhel:
    runs-on: ubuntu-latest
    name: Test on RHEL
    container:
      image: docker.io/library/rockylinux:8
    needs: build_on_rhel
    steps:
    - name: Install git
      run: dnf -y install git
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      run: tests/ci/prepare-ci-environment.sh
    - id: files
      uses: jitterbit/get-changed-files@v1
    - uses: actions/download-artifact@v3
      with:
        name: rhel-rpms
        path: /home/ohpc/rpmbuild/RPMS
    - name: Run CI Tests
      run: |
        . /etc/profile.d/lmod.sh
        chown ohpc -R tests
        tests/ci/setup_slurm_and_run_tests.sh ohpc ${{ steps.files.outputs.added_modified }}

  build_on_leap:
    runs-on: ubuntu-latest
    name: Build on LEAP
    container:
      image: registry.opensuse.org/opensuse/leap:15.3
    steps:
    - name: Install git
      run: zypper -n install git
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      run: tests/ci/prepare-ci-environment.sh
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Validate Build
      run: |
        . /etc/profile.d/lmod.sh
        tests/ci/run_build.py ohpc ${{ steps.files.outputs.added_modified }}

  build_on_openEuler:
    runs-on: ubuntu-latest
    container:
      image: docker.io/openeuler/openeuler:22.03-lts
    steps:
    - name: Setup
      run: |
        dnf install -y http://121.36.3.168:82/home:/huangtianhua:/ohpc/standard_x86_64/x86_64/ohpc-release-2-1.oe2203.ohpc.2.0.0.x86_64.rpm openEuler-release dnf-plugins-core git python3 findutils rpm-build wget gawk
        dnf install -y https://github.com/ohpc-openeuler/ohpc/releases/download/2.x-openEuler-gcc12-aarch64/gnu12-compilers-ohpc-12.2.0-1.ohpc.2.0.0.x86_64.rpm
        yum install -y lmod-ohpc ohpc-buildroot
        adduser ohpc
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Validate Build
      run: |
        . /etc/profile.d/lmod.sh
        tests/ci/run_build.py ohpc ${{ steps.files.outputs.added_modified }}
